### ISSUE TITLE
Empty SparseArray on first attempt

### ISSUE THREAD

**Issue by Ashish-Bansal** [HaarigerHarald/android-youtubeExtractor#2]
Hi,

I was using this library in an application and sometimes it gives empty SparseArray in first attempt but on trying again for same video, it gives all the links. I know it sounds weird but it happens a lot of times.

Do you know what could be the problem ?

Thanks!

**Comment by HaarigerHarald** [comment]
Can you give me a sample video where this behavior occurs. I can't reproduce it with the unit tests.

**Comment by Ashish-Bansal** [comment]
It happens with vevo vidoes :

Adele When we were Young (AdeleVevo) : https://www.youtube.com/watch?v=DDWKuo3gXMQ
Adele Hello (AdeleVevo) : https://www.youtube.com/watch?v=YQHsXMglC9A

It doesn't happen always, only sometimes.

**Comment by HaarigerHarald** [comment]
Still can't reproduce it. But since it only happens on signature enciphered videos maybe https://github.com/HaarigerHarald/android-youtubeExtractor/blob/88f5fbdc03d94d80963a56c77b78569e779211a3/youtubeExtractor/src/main/java/at/huber/youtubeExtractor/YouTubeUriExtractor.java#L323 is causing it.

Can you try to increase it to 5-10 seconds and report back if that fixes it.

Little insight, afaik there is no way to capture a js error in a webview. The webview just won't respond on an error and without the wait there would be a deadlock. The first start of a webview is usually slower than consecutive ones, which would explain why it works when you try it again.

**Comment by Ashish-Bansal** [comment]
Yes, that seems to fix the issue.
